RecipeBox/Controllers/RecipiesController.cs
using Microsoft.AspNetCore.Mvc;
using RecipeBox.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace RecipeBox.Controllers
{
  [Authorize]
  public class RecipiesController : Controller
  {
    private readonly RecipeBoxContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public RecipiesController(UserManager<ApplicationUser> userManager, RecipeBoxContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userRecipies = _db.Recipies.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userRecipies);
    }


    //[Authorize]
    public ActionResult Create()
    {
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Tag", "Description"); //dont think we need ', "Description"'
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Recipe recipe, int CategoryId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      recipe.User = currentUser;
      _db.Recipies.Add(recipe);
      _db.SaveChanges();
      if (CategoryId != 0)
      {
        _db.CategoryRecipe.Add(new CategoryRecipe() { CategoryId = CategoryId, RecipeId = recipe.RecipeId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    // public ActionResult Details(int id)
    // {
    //   var thisRecipe = _db.Recipe
    //     .Include(Recipe => recipe.JoinEntities)
    //     .ThenInclude(join => join.Category)
    //     .Include(recipe => recipe.User)
    //     .FirstOrDefault(recipe => recipe.RecipeId == id);
    //   var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
    //   ViewBag.IsCurrentUser = userId != null ? userId == thisRecipe.User.Id : false;
    //   return View(thisRecipe);
    // }

    public ActionResult Details(int id)
    {
      var thisRecipe = _db.Recipies
        .Include(Recipe => Recipe.JoinEntities)
        .ThenInclude(join => join.Category)
        .FirstOrDefault(recipe => recipe.RecipeId == id);
      return View(thisRecipe);
    }


    public ActionResult Edit(int id)
    {
      var thisRecipe = _db.Recipies.FirstOrDefault(recipe => recipe.RecipeId == id);
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
      return View(thisRecipe);
    }

    [HttpPost]
    public ActionResult Edit(Recipe recipe, int CategoryId)
    {
      if (CategoryId != 0)
      //Notice that we again use a conditional in the case that no Categories yet exist or are being used.
      {
        _db.CategoryRecipe.Add(new CategoryRecipe()
        { CategoryId = CategoryId, RecipeId = recipe.RecipeId });
      }
      _db.Entry(recipe).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddCategory(int id)
    {
      var thisRecipe = _db.Recipies.FirstOrDefault(recipe => recipe.RecipeId == id);
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Tag");//Tag
      return View(thisRecipe);
    }

    [HttpPost]
    public ActionResult AddCategory(Recipe recipe, int CategoryId)
    {
      if (CategoryId != 0)
      {
        _db.CategoryRecipe.Add(new CategoryRecipe() { CategoryId = CategoryId, RecipeId = recipe.RecipeId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisRecipe = _db.Recipies.FirstOrDefault(recipe => recipe.RecipeId == id);
      return View(thisRecipe);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisRecipe = _db.Recipies.FirstOrDefault(recipe => recipe.RecipeId == id);
      _db.Recipies.Remove(thisRecipe);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteCategory(int joinId)
    {
      var joinEntry = _db.CategoryRecipe.FirstOrDefault(entry => entry.CategoryRecipeId == joinId);
      _db.CategoryRecipe.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

RecipeBox/Views/Recipies/AddCategory.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h2>Add a Category</h2>

<h4>Add a category to this recipe: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RecipeId)

  @Html.Label("Select category")
  @Html.DropDownList("CategoryId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

RecipeBox/Views/Recipies/Create.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h4>Add a new Recipe:</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model=>model.Name)
  @Html.TextBoxFor(model=>model.Name)
  <hr />
  <p>
  @Html.LabelFor(model=>model.Rating): (1-5)
  @* @Html.TextBoxFor(model=>model.Rating) *@
  @Html.RadioButtonFor(m => m.Rating, "1", new { @checked = true })&nbsp;
  @Html.RadioButtonFor(m => m.Rating, "2")&nbsp;
  @Html.RadioButtonFor(m => m.Rating, "3")&nbsp;
  @Html.RadioButtonFor(m => m.Rating, "4")&nbsp;
  @Html.RadioButtonFor(m => m.Rating, "5")
</p>
  <hr />
  @Html.LabelFor(model=>model.Ingredients)
  @Html.TextBoxFor(model=>model.Ingredients)
  <hr />
  @Html.LabelFor(model=>model.Instructions)
  @Html.TextBoxFor(model=>model.Instructions)
  <hr />
  @Html.Label("Select Category")
  @Html.DropDownList("CategoryId")

  <input type="submit" value="Add new Recipe" class="btn btn-default" />
}
<br>
<p>@Html.ActionLink("Show all recipies", "Index")</p>
<hr />

RecipeBox/Views/Recipies/Delete.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h2>Are you sure you want to delete this recipe?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name);
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

RecipeBox/Views/Recipies/Details.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h2>Recipe Details:</h2>
<h4>
  <strong>@Html.DisplayNameFor(model=>model.Name):</strong> @Html.DisplayFor(model=>model.Name)<br><br>
  <strong>@Html.DisplayNameFor(model=>model.Rating):</strong> @Html.DisplayFor(model=>model.Rating)<br><br>
  <strong>@Html.DisplayNameFor(model=>model.Ingredients):</strong>
  @Html.DisplayFor(model=>model.Ingredients)<br><br>
  <strong>@Html.DisplayNameFor(model=>model.Instructions):</strong> @Html.DisplayFor(model=>model.Instructions)
</h4>
<br>
@if (@Model.JoinEntities.Count == 0)
{
  <p>This recipe does not belong to any categories</p>
}
else
{
  <h4>Categories the recipe belongs to:</h4>
  <ul>
  @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Category.Tag</li>
      @using (Html.BeginForm("DeleteCategory", "Recipies"))
      {
        @Html.Hidden("joinId", @join.CategoryRecipeId)
        <input type="submit" value="Delete" />
      }
    }
  </ul>
}

<p>@Html.ActionLink("Add a Category", "AddCategory", new { id = Model.RecipeId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Item", "Edit", new { id = Model.RecipeId })</p>@*//feel like this should be 'CategoryId'*@
<p>@Html.ActionLink("Delete Item", "Delete", new { id = Model.RecipeId })</p>

RecipeBox/Views/Recipies/Edit.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h2>Edit</h2>

<h4>Edit this recipe: @Html.DisplayFor(model => model.Name)/h4>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.RecipeId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    @Html.LabelFor(model => model.Rating)
    @Html.EditorFor(model => model.Rating)

    @Html.LabelFor(model => model.Ingredients)
    @Html.EditorFor(model => model.Ingredients)

    @Html.LabelFor(model => model.Instructions)
    @Html.EditorFor(model => model.Instructions)

    @Html.Label("Select category")
    @Html.DropDownList("CategoryId")

    <input type="submit" value="Save" />
  }

  <p>@Html.ActionLink("Back to list", "Index")</p>

RecipeBox/Views/Recipies/Index.cshtml
@{
  Layout = "_Layout";
}

@using RecipeBox.Models;
@model IEnumerable<RecipeBox.Models.Recipe>

<h1>Recipies for @User.Identity.Name</h1>


@if (Model.Any())
{
  <ul>
  @foreach (Recipe recipe in Model)
    {
      <li>@Html.ActionLink($"{recipe.Name}", "Details", new { id = recipe.RecipeId })</li>
    }
  </ul>
}
else
{
  <h3>No recipies have been added yet!</h3>
}

<p>@Html.ActionLink("Add new recipe", "Create")</p>
@* <p>@Html.ActionLink("Home", "Index", "Home")</p> *@